MONGODB_HOST: mongodb-{{ env }}.cloudskills.fun
REDIS_HOST: redis-{{ env }}.cloudskills.fun
CATALOGUE_HOST: catalogue-{{ env }}.cloudskills.fun
CART_HOST: cart-{{ env }}.cloudskills.fun
USER_HOST: user-{{ env }}.cloudskills.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.cloudskills.fun
MYSQL_HOST: mysql-{{ env }}.cloudskills.fun
SHIPPING_HOST: shipping-{{ env }}.cloudskills.fun
PAYMENT_HOST: payment-{{ env }}.cloudskills.fun