- name: Disabling default redis
  ansible.builtin.command: dnf module disable redis -y
  
- name: Enabling  redis 7
  ansible.builtin.command: dnf module disable redis -y

- name: Installing Redis
  ansible.builtin.package:
         name: redis
         state: present

- name: Allowing Remote connection
  ansible.builtin.replace:
       path: /etc/redis/redis.conf
       regexp: '127.0.0.1'
       replace: '0.0.0.0'
  
- name: Update protected mode
  ansible.builtin.lineinfile:
       path: /etc/redis/redis.conf
       regexp: 'protected-mode'
       line: 'protected-mode no'

- name: Restart Service
  ansible.builtin.service:
           name: redis
           state: started
           enabled: yes

#ansible-playbook -i inventory.ini main.yaml -e "component=redis"