
[frontend]
localhost
[local]
localhost

[local:vars]
COURSE=Ansible
DURATION=10HRS

[mongodb]
localhost


[redis]
localhost

[mysql]
localhost

[rabbitmq]
localhost

[catalogue]
localhost
[cart]
localhost
[user]
localhost
[shipping]
localhost
[frontend]
localhost
[payment]
localhost

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321