- name: copying the repo
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Installing RabbitMQ 
  ansible.builtin.package:
      name: rabbitmq-server
      state: present

- name: Enable and start the Service 
  ansible.builtin.service:
          name: rabbitmq-server
          state: started
          enabled: yes

- name: Creating User with full permissions
  community.rabbitmq.rabbitmq_user:
    user: roboshop 
    password: roboshop123
    permissions:
    - vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
    state: present
